### ISSUE TITLE
Add types field to package.json

### ISSUE THREAD

**Issue by yuri-zaitsev** [seznam/compose-react-refs#10]
Hi! I get an error:

`
 TS6059: File '/node_modules/@seznam/compose-react-refs/composeRefs.js' is not under 'rootDir'. 'rootDir' is expected to contain all source files.
`

Please, add field "types" to package json.

`"types": "./composeRefs.d.ts",`

**Comment by jurca** [comment]
Published as `@seznam/compose-react-refs@1.0.6`.

Sorry for the long delay, I wasn't feeling well.
