### ISSUE TITLE
Distribution includes spread operator and is not compatible with IE

### ISSUE THREAD

**Issue by jonkelling** [seznam/compose-react-refs#2]
Sorry for the short description--I'm assuming that the title is enough :)

**Comment by jonkelling** [comment]
@jurca Hello. Any chance you could take a look at this and the pull request? Thanks!

**Comment by jurca** [comment]
Hello and sorry for taking so long to reply.

Since this does not increase the size of the generated code much, I'm going to accept this change. Thanks for the PR!

**Comment by jurca** [comment]
I've just published @seznam/compose-react-refs@1.0.2 with your PR applied.

Thank you for your contribution!

**Comment by jonkelling** [comment]
Thank you for the quick turnaround. It's much appreciated!
