### ISSUE TITLE
[RFC] Allow passing `undefined` as an argument to `composeRefs`

### ISSUE THREAD

**Issue by andrewtpoe** [seznam/compose-react-refs#5]
I am building a component library where I occasionally need to merge refs. High level components typically use `forwardRef` to gain access to the `ref` prop, but I also frequently need to allow other named ref props. Sometimes, those other named props need to be combined with refs from hooks that all refer to the same element. The trouble is, the alternative ref prop is typically optional.

I'd love to see `composeRef` filter undefined/ non-ref values before composing them. That would allow me to simply `composeRef(refForUseByComponent, passThroughRefThatMayNotExist)` instead of requiring the fancy filtering/ fallback logic I'm having to use now.

Otherwise, thanks for a great tool. This has really solved some headaches for me.

**Comment by jurca** [comment]
Hello,

thank you for your suggestion. I think that what you propose sounds reasonable, so I'll look into it. Maybe even today :).

I'll let you know of any progress.

**Comment by StJohn3D** [comment]
Also want to say thank you for this library. Wish it was MIT instead of ISC but I'm hoping legal will approve ISC as well, just hate having to ask.
Anyway about possibly undefined external ref, this is currently working for me. My test that consumes this component isn't passing a ref and I'm not getting any undefined errors.

> "@seznam/compose-react-refs": "1.0.2",

<details>
<summary>Expand to see the code...</summary>
I'm not posting the CSS but it's your typical custom checkbox where the input is hidden and puppeteered by a label element. For people who want a controlled checkbox experience, they need to use the onClick event, so I'm using this library to allow people to still pass a ref to the input element. While the component uses it's own internal ref to pass click events on the label down to the input element.

```tsx
export interface ICheckboxProps extends React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement> {
  id: string
  label?: string
  value?: string
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void
  onClick?: (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => void
  disabled?: boolean
  className?: string
  checked?: boolean
  defaultChecked?: boolean
  styleInverted?: boolean
}

const MyCheckbox = React.forwardRef<HTMLInputElement, ICheckboxProps>((props, forwardedInputRef) => {
  const inputRef = useRef(null as HTMLInputElement | null)  // 👈🏻👈🏻👈🏻👈🏻

  const handleClick = () => {
    if (inputRef.current instanceof HTMLElement) {
      inputRef.current.click()   // 👈🏻👈🏻👈🏻👈🏻
    }
  }

  return (
    <div
      className={classNames("custom-control", "custom-checkbox",
        props.className, props.styleInverted ? "custom-checkbox-inverted" : undefined
      )}
    >
      <input
        id={props.id}
        type="checkbox"
        className="custom-control-input"
        value={props.value}
        checked={props.checked}
        defaultChecked={props.defaultChecked}
        disabled={props.disabled}
        onChange={props.onChange}
        onClick={props.onClick}
        ref={composeRefs(inputRef, forwardedInputRef) /*👈🏻👈🏻👈🏻👈🏻 */ }
      />
      <label
        className="custom-control-label"
        htmlFor={props.id}
        onClick={handleClick /*👈🏻👈🏻👈🏻👈🏻 */}
      >
        {props.label}
      </label>
    </div>
  )
})

MyCheckbox.displayName = "Checkbox"

export const Checkbox = MyCheckbox
```
</details>

**Comment by jurca** [comment]
I've just published @seznam/compose-react-refs@1.0.3 which allows `undefined`s to be passed into the `composeRefs` function as well. I hope you'll like it :).

The implementation always filtered non-refs, [this code did the filtering](https://github.com/seznam/compose-react-refs/blob/master/composeRefs.ts#L21-L38). On a second thought, maybe I should explicitly say so in the documentation..? I'll try to update in on Monday.

@StJohn3D The ISC license is legally equivalent to the MIT license, it just has a shorter text. I think you will be fine :).

Regarding undefined refs - React always uses `null` as a ref value, not `undefined`, when a ref is not provided. That is the reason you were not getting any type errors. The type signature of a functional ref-forwarding component documents this behavior as well:

```typescript
    interface RefForwardingComponent<T, P = {}> {
        (props: PropsWithChildren<P>, ref: Ref<T>): ReactElement | null;
        propTypes?: WeakValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
    }
```

**Comment by jurca** [comment]
@andrewtpoe I've just published 1.0.4.

Would you please let me know if the documentation is clear and easy to understand? Especially the fact that refs are filtered, so that no filtering on your part is necessary.

Thank you for your feedback.

**Comment by andrewtpoe** [comment]
Yes, thank you! I think this will work very nicely for my use case now.

**Comment by jurca** [comment]
I'm grad to hear it!

Thank you for filing this issue and helping me to make this lib better :).
